# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
repos:

  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.3.0
    hooks:
      - id: check-added-large-files
      - id: check-toml
      - id: check-yaml
      - id: detect-private-key
      - id: end-of-file-fixer
      - id: requirements-txt-fixer
      - id: trailing-whitespace
        exclude: ^tests/.*data/.*$
      - id: check-json
      - id: name-tests-test
        args: [--pytest-test-first]
  - repo: https://github.com/astral-sh/ruff-pre-commit
    # Ruff version.
    rev: v0.12.11
    hooks:
      # Run the linter.
      - id: ruff
        args:
          - "--select=ALL"
          - "--ignore=RUF100,RUF013,BLE001,COM812,ISC001,D100,D101,D102,D104,D105,D106,D107,D200,D203,D205,D211,D212,D400,D401,D415,E203,E266,E501,ANN001,ANN101,ANN102,ANN201,ANN204,ANN206,ANN401,S101,S104,S602,ERA001,PGH003,PLR0913,PLR2004,PLC0415,TRY004,TRY400,TRY003,N803,N815,EM101,EM102,INP001,F401,F821,DTZ005,SIM102,PERF401"
          - "--line-length=100"
      # Run the formatter.
      - id: ruff-format
  - repo: https://github.com/PyCQA/pylint
    rev: v3.3.8
    hooks:
      - id: pylint
        args:
          - "--rcfile=pylintrc"
          # run pylint across multiple cpu cores to speed it up-
          # https://pylint.pycqa.org/en/latest/user_guide/run.html?#parallel-execution to know more
          - "--jobs=0"
          - "--fail-under=9.0" # minimum score to pass pylint

  - repo: https://github.com/PyCQA/bandit
    rev: 1.8.6
    hooks:
      - id: bandit
        args: ["-c", "pyproject.toml", "-r", "."]
        additional_dependencies: ["bandit[toml]"]
