# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
repos:
  - repo: https://github.com/pycqa/isort
    rev: 6.0.1
    hooks:
      - id: isort
        args: ["--settings-path=pyproject.toml"]
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.3.0
    hooks:
      - id: check-added-large-files
      - id: check-toml
      - id: check-yaml
      - id: detect-private-key
      - id: end-of-file-fixer
      - id: requirements-txt-fixer
      - id: trailing-whitespace
        exclude: ^tests/.*data/.*$
      - id: check-json
      - id: name-tests-test
        args: [--pytest-test-first]
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.12.11
    hooks:
      - id: ruff
        args:
          - "--select=ALL"
          - "--ignore=I001,BLE001,COM812,ISC001,D100,D101,D104,D105,D107,D205,D211,D212,D400,D415,E203,E266,ANN201,ANN204,S101,S602,ERA001,PLR0913,PLR2004,N803,N815,EM101,TRY003,INP001,RUF100,RUF013,D102,D106,D200,D203,D401,E501,ANN001,ANN101,ANN102,ANN206,ANN401,S104,PGH003,PLC0415,TRY004,TRY400,EM102,F401,F821,DTZ005,SIM102,PERF401"
          - "--line-length=100"
      - id: ruff-format
  - repo: https://github.com/PyCQA/pylint
    rev: v3.3.8
    hooks:
      - id: pylint
        args:
          - "--rcfile=pylintrc"
          # run pylint across multiple cpu cores to speed it up-
          # https://pylint.pycqa.org/en/latest/user_guide/run.html?#parallel-execution to know more
          - "--jobs=0"
          - "--fail-under=9.0" # minimum score to pass pylint

  - repo: https://github.com/PyCQA/bandit
    rev: 1.8.6
    hooks:
      - id: bandit
        args: ["-c", "pyproject.toml", "-r", "."]
        additional_dependencies: ["bandit[toml]"]
