services:
  postgres:
    image: postgres:15-alpine
    container_name: eq-prepaid-postgres
    restart: unless-stopped
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - "${POSTGRES_PORT}:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - eq-prepaid-network

  redis:
    image: redis:7-alpine
    container_name: eq-prepaid-redis
    restart: unless-stopped
    command: redis-server --requirepass ${REDIS_PASSWORD}
    ports:
      - "${REDIS_PORT}:6379"
    volumes:
      - redis_data:/data
    networks:
      - eq-prepaid-network

  adminer:
    image: adminer:latest
    container_name: eq-prepaid-adminer
    restart: unless-stopped
    ports:
      - "${ADMINER_PORT}:8080"
    environment:
      ADMINER_DEFAULT_SERVER: postgres
    depends_on:
      - postgres
    networks:
      - eq-prepaid-network

volumes:
  postgres_data:
  redis_data:

networks:
  eq-prepaid-network:
    driver: bridge
