"""
Initial migration: create sections and rules tables

Revision ID: beb56d8e00ed
Revises:
Create Date: 2025-09-06 15:52:51.330648

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "beb56d8e00ed"
down_revision: str | Sequence[str] | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "rules",
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.Column("profile_type", sa.Enum("PREPAID", "HYBRID", name="profiletype"), nullable=False),
        sa.Column(
            "balance_type", sa.Enum("MAIN_BALANCE", "CRED", name="balancetype"), nullable=False
        ),
        sa.Column(
            "status",
            sa.Enum("DRAFT", "IN_PRODUCTION", "TO_VALIDATE", name="status"),
            nullable=False,
        ),
        sa.Column("section_id", sa.UUID(), nullable=False),
        sa.Column("database_table_name", postgresql.ARRAY(sa.String()), nullable=False),
        sa.Column("config", sa.JSON(), nullable=False),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "sections",
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.Column("slug", sa.String(length=255), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("status", sa.Enum("ACTIVE", "INACTIVE", name="sectionstatus"), nullable=False),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=True),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("slug"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("sections")
    op.drop_table("rules")
    # ### end Alembic commands ###
